// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfcwwvaaupipdfrqxlaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmY3d3dmFhdXBpcGRmcnF4bGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjMzODUsImV4cCI6MjA2ODIzOTM4NX0.kO73ZSopaQqt0mShRyvn120RSXnW27eKkakzmg-QcmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});